server:
  port: 9527

spring:
  application:
    name: cloud-gateway #以微服务注册进consul或nacos服务列表内
  cloud:
    consul: #配置consul地址
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
#        - id: pay_routh3
#          uri: lb://cloud-payment-service
#          predicates:
##             - Path=/XYZ/abc/{segment}  配合setPath的{segment取代;上下文{代称一致}}
##            - Path=/gateway/filter/**   为配合prefix过滤;cuz注释pay;
#            - Path=/pay/gateway/filter/**
#          filters:
#            - RedirectTo=302,https://www.youtube.com/  重定向到youtube;
#            - SetPath=/pay/gateway/{segment}
#            - PrefixPath=/pay
#            - AddRequestHeader=X-Request-atguigu1,atguiguValue1
#            - AddRequestHeader=X-Request-atguigu2,atguiguValue2
#            - AddResponseHeader=X-Request-atguigu,BlueResponse
#            - SetResponseHeader=Date,2099-11-11
#            - RemoveResponseHeader=Content-Type
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
         # uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由
#            - After=2024-04-07T09:46:38.448160400+08:00[Asia/Shanghai]
#           # - Cookie=username,HHH
            # - Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
#           # - Host=**.atguigu.com
#            - Query=username, \d+
#            - Method=GET,POST
#            - My=gold
#            - name: My
#              args:
#                 userType: gold
          # - Before 同理
          # - Between=2024-04-07T09:46:38.448160400+08:00[Asia/Shanghai],2024-04-07T09:46:38.448160400+08:00[Asia/Shanghai]
          # 即可;
          filters:
            - My=atguigu
            - AddRequestHeader=X-Request-atguigu1,atguiguValue1
        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service
          #uri: http://localhost:8001                #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由
#      default-filters:
#        - AddResponseHeader=X-Response-Default-Red,Default-Blue  配置在这里相当于全局通用;自定义变成global;
